### ISSUE TITLE
Link to Staking Deposit CLI not working

### ISSUE THREAD

**Issue by sameignatovich** [ephemery-testnet/ephemery-genesis#45]
Hello!

It seems that the repository https://github.com/remyroy/staking-deposit-cli no longer exists (or may have been made private recently). Could you please update the instructions for validators in the main README.md?

Thanks!

**Comment by remyroy** [comment]
Good catch. I think we can use ethstaker-deposit-cli from https://github.com/eth-educators/ethstaker-deposit-cli/releases/tag/v0.5.0 now. It has full Ephemery support and it is the most supported tool to help with these kind of tasks.
